apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: redmine-cronjob
spec:
 schedule: "0 * * * SUN-FRI"
 concurrencyPolicy: Replace
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - image: gcr.io/youtube-api-168617/redmine-1:3.1
           name: redmine-cron
           volumeMounts:
           - name: redmine-persistent-storage
             mountPath: /usr/src/redmine/files
             readOnly: true
           command: ["python3",  "get_projects.py"]
         volumes:
         - name: redmine-persistent-storage
           persistentVolumeClaim:
             claimName: nfs
             readOnly: true
         restartPolicy: Never
